In [2]:
import numpy as np

t = np.random.randint(0, 4, 10)
print(t)


t = t[:, None]
clases = np.arange(0, 4)[None, :]
one_hot_t = (t == clases) * 1.
print(one_hot_t)

[2 0 3 0 3 3 0 0 2 1]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
