In [1]:
import numpy as np
import pandas as pd

In [2]:
np.ones((4))

array([1., 1., 1., 1.])

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
my_ones_1 = np.ones(10)
my_ones_2 = np.ones(10) * 2
my_ones_3 = np.ones(10) * 3

In [5]:
my_ones_1, my_ones_2, my_ones_3

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]))

In [6]:
my_todos = np.zeros((10,3))

my_todos[:,0] = my_ones_1
my_todos[:,1] = my_ones_2
my_todos[:,2] = my_ones_3

In [7]:
my_todos, pd.DataFrame(my_todos)

(array([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]),
      0    1    2
 0  1.0  2.0  3.0
 1  1.0  2.0  3.0
 2  1.0  2.0  3.0
 3  1.0  2.0  3.0
 4  1.0  2.0  3.0
 5  1.0  2.0  3.0
 6  1.0  2.0  3.0
 7  1.0  2.0  3.0
 8  1.0  2.0  3.0
 9  1.0  2.0  3.0)

In [8]:
pd.DataFrame(my_todos, columns = ["IBEX", "DAXX", "EUROSTOXX"]).T

0    1    2    3    4    5    6    7    8    9
IBEX       1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
DAXX       2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
EUROSTOXX  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0

In [9]:
my_todos[:,1]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [10]:
my_todos.shape

(10, 3)

In [11]:
data = np.zeros((500,10,3))

In [12]:
data.shape

(500, 10, 3)

In [13]:
for i in range(data.shape[0]):
    data[i] = my_todos

In [14]:
data.shape

(500, 10, 3)

In [15]:
data_dim = np.zeros((500,10,1,3))
data_dim.shape

(500, 10, 1, 3)

In [16]:
data_dim[:,:,0,0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
my_ones_1.shape

(10,)

In [17]:
for i in range(data.shape[0]):
    data_dim[:,:,0,0] = my_ones_1
    data_dim[:,:,0,1] = my_ones_2
    data_dim[:,:,0,2] = my_ones_3

In [18]:
data_dim.shape

(500, 10, 1, 3)

In [19]:
data_dim[0,:,0,0], data_dim[0,:,0,1], data_dim[0,:,0,2]

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]))